apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-app
  template:
    metadata:
      labels:
        app: flight-app
    spec:
      containers:
      - name: flight-container
        image: mahesh2452/flight-project:latest
        ports:
        - containerPort: 80
